### ISSUE TITLE
hey guys :)

### ISSUE THREAD

**Issue by npfoss** [michmich112/teleporter#18]
Hi! Gather dev here --

This is fantastic and I love it XD

Just fyi, we're going to fix the ability to teleport soonish (in favor of the new named spawn tiles that you can respawn to), so it will break this implementation but most of the stuff will still be possible. Will send more details [here](https://forms.gle/GunG5mMNsXPaUiRQ7) a week before that happens.

<3,
--Nate

**Comment by michmich112** [comment]
Hey Nate,
Thanks for reaching out and the heads up, just subscribed to the updates. We will deprecate in line with your rollout. :)
Keep up the great work 🦾
-- Mich
